// hip_recfg_clk_in.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module hip_recfg_clk_in (
		input  wire  in_clk,  //  in_clk.clk, Clock Input
		output wire  out_clk  // out_clk.clk, Clock Output
	);

	assign out_clk = in_clk;

endmodule
