// rnr_ial_sip_clkgen_pll.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module rnr_ial_sip_clkgen_pll (
		input  wire  refclk,   //  refclk.clk
		output wire  locked,   //  locked.export
		input  wire  rst,      //   reset.reset
		output wire  outclk_0, // outclk0.clk
		output wire  outclk_1  // outclk1.clk
	);

	intel_rtile_cxl_top_cxltyp2_ed_altera_iopll_2000_u7qu56a rnr_ial_sip_clkgen_pll (
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.locked   (locked),   //  output,  width = 1,  locked.export
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.outclk_0 (outclk_0), //  output,  width = 1, outclk0.clk
		.outclk_1 (outclk_1)  //  output,  width = 1, outclk1.clk
	);

endmodule
